version: '3'

services:
  filebeat:
    container_name: filebeat
    image: bargenson/filebeat:latest
    restart: always
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    environment:
     - LOGSTASH_HOST=logstash
     - LOGSTASH_PORT=5044
     - SHIPPER_NAME=my-filebeat
